#include <stm32f407xx.h>
#include "InitGPIO.h"

void LCD5110_GPIO_Init(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOCEN;
	
	GPIOA->MODER |= GPIO_MODER_MODER8_0;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8;
	GPIOA->PUPDR = 0;
	GPIOA->OTYPER = 0;
	
	GPIOC->MODER |= GPIO_MODER_MODER7_0 | GPIO_MODER_MODER7_0 | GPIO_MODER_MODER8_0 | GPIO_MODER_MODER9_0;
	GPIOC->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR8;
	GPIOC->PUPDR = 0;
	GPIOC->OTYPER = 0;
}
